### ISSUE TITLE
[功能] 将 `@qq号` 改为 `@名称`

### ISSUE THREAD

**Issue by ApliNi** [ApliNi/Chat2QQ#1]
预计会使用 MiraiMC 的玩家信息缓存, 或者添加一个数据库...

不知道什么时候实现.

**Comment by QianFuv** [comment]
刚想来提这个issue 没想到有了hhh  mirai应该有根据qq号获取群名片的接口吧

**Comment by ApliNi** [comment]
我没找到, 但我找到了获取一个群内所有账户信息的方法. 我会在Chat2QQ中缓存它用来提取名称

**Comment by QianFuv** [comment]
但是如果是几百人的群是不是对性能会有影响
其中还涉及群昵称的问题

**Comment by ApliNi** [comment]
不至于, 有很多优化方案, 比如散列表和内存数据库

**Comment by QianFuv** [comment]
那就看你的本事了hhh

**Comment by QianFuv** [comment]
还有就是指令的问题  现在原版指令反馈好像是做不到是吧

**Comment by ApliNi** [comment]
我做不到

**Comment by QianFuv** [comment]
慢慢来吧  不急  这个项目你会一直维护吗

**Comment by ApliNi** [comment]
不确定, 我不知道以后是否还有时间研究这些
我会尽量把软件写可靠一些吧

**Comment by QianFuv** [comment]
嗯嗯加油 我一直在默默关注

**Comment by ApliNi** [comment]
此功能的测试版已完成, 测试完成后我将发布正式版 🎉

https://github.com/ApliNi/Chat2QQ/actions/runs/4072695746

**Comment by QianFuv** [comment]
> 此功能的测试版已完成, 测试完成后我将发布正式版 🎉
> 
> https://github.com/ApliNi/Chat2QQ/actions/runs/4072695746

感激

**Comment by ApliNi** [comment]
已解决: https://github.com/ApliNi/Chat2QQ/releases/tag/1.7.10

**Comment by QianFuv** [comment]
> 已解决: https://github.com/ApliNi/Chat2QQ/releases/tag/1.7.10

太帅了！
mirai的那个选项在哪里开启呢

**Comment by ApliNi** [comment]
在miraiMC的配置文件里

**Comment by ApliNi** [comment]
我刚发现我只添加了自己的QQ号和群号, 这个功能应该无效
现在修复...

**Comment by ApliNi** [comment]
https://github.com/ApliNi/Chat2QQ/releases
