### ISSUE TITLE
为co插件实现已弃用的 .spigot().sendMessage()

### ISSUE THREAD

**Issue by diaoyugan** [ApliNi/Chat2QQ#18]
例如我在QQ使用list命令时 服务器内有玩家 但仍然输出 运行无返回指令
或者在QQ群使用coreprotect lookup时 只会返回第一行的结果 其他的结果均不显示

**Comment by ApliNi** [comment]
> 例如我在QQ使用list命令时 服务器内有玩家 但仍然输出 运行无返回指令

这是一个已知问题, 插件没法捕获原版的指令输出消息 #4, 解决方案有: 
1. 使用其他格式化list指令消息的插件, 比如Ess
2. 使用自动回复功能 [自动回复](https://github.com/ApliNi/Chat2QQ#%E8%87%AA%E5%8A%A8%E5%9B%9E%E5%A4%8D)

---

> 或者在QQ群使用coreprotect lookup时 只会返回第一行的结果 其他的结果均不显示

这个可能是coreprotect使用特殊的方法向玩家发送消息, 或者coreprotect直接将消息输出到了控制台
等我研究一段时间

**Comment by ApliNi** [comment]
> 或者在QQ群使用coreprotect lookup时 只会返回第一行的结果 其他的结果均不显示

这个可能解决不了, 因为没法简单的通过代码模拟出真实的玩家及其数据  
一个相关的问题: https://www.spigotmc.org/threads/simulate-a-fake-player-to-run-commands.410153/

我会找找有没有方法解决它, 但不是现在

**Comment by QianFuv** [comment]
或许可以直接生成一个假人然后抓取他的消息记录？

**Comment by ApliNi** [comment]
> 或许可以直接生成一个假人然后抓取他的消息记录？

我有想过这个方法，但我认为这样做成本很高，所以不会在短时间内实现它

https://github.com/taooceros/PlayerSimulator

**Comment by ApliNi** [comment]
我研究了一下co插件的代码, co插件使用了已弃用的消息发送函数, 而我没有实现它, 已在开发版本中修复: https://github.com/ApliNi/Chat2QQ/actions/runs/4678989858

我稍后会将它发布
