### ISSUE TITLE
直接连接 go-cqhttp

### ISSUE THREAD

**Issue by ApliNi** [ApliNi/Chat2QQ#22]

**Comment by ApliNi** [comment]
MiraiMC已支持扫码登录!

**Comment by LittleChest** [comment]
仍然有必要连接go-cqhttp 比如一个其它娱乐性机器人（例如NoneBot加了一堆插件）和Chat2QQ+共同处理消息

**Comment by ApliNi** [comment]
> 仍然有必要连接go-cqhttp 比如一个其它娱乐性机器人（例如NoneBot加了一堆插件）和Chat2QQ+共同处理消息

我有想过这个, go-cqhttp 很稳定, 并且通过它能实现给图片添加点击打开链接之类的功能, 但这么久没做出来因为有些懒 (

**Comment by LittleChest** [comment]
### off-topic
哦对了，顺便问一下MiraiMC怎么扫码登录，如果不输入密码还是会报错

**Comment by ApliNi** [comment]
> 仍然有必要连接go-cqhttp 比如一个其它娱乐性机器人（例如NoneBot加了一堆插件）和Chat2QQ+共同处理消息

不过新版的 MiraiMC 使用不同于 go-cqhttp 的登录协议, 能同时登录一个账号, 可以试试.

**Comment by LittleChest** [comment]
> > 仍然有必要连接go-cqhttp 比如一个其它娱乐性机器人（例如NoneBot加了一堆插件）和Chat2QQ+共同处理消息
> 
> 不过新版的 MiraiMC 使用不同于 go-cqhttp 的登录协议, 能同时登录一个账号, 可以试试.

所有协议全部error 237 go-cqhttp用扫码没问题（不填写签名api）

**Comment by ApliNi** [comment]
> 所有协议全部error 237 go-cqhttp用扫码没问题（不填写签名api）

是扫码登录吗? 我这边用着挺稳定的, 就是好像每个月要重新登录一次.

**Comment by LittleChest** [comment]
> > 所有协议全部error 237 go-cqhttp用扫码没问题（不填写签名api）
> 
> 是扫码登录吗? 我这边用着挺稳定的, 就是好像每个月要重新登录一次.

https://github.com/ApliNi/Chat2QQ/issues/22#issuecomment-1635319100
密码
