### ISSUE TITLE
考虑移植fabric？

### ISSUE THREAD

**Issue by QianFuv** [ApliNi/Chat2QQ#32]
目前模组端消息转发模组有且仅有群服互联可用，但是效果并不理想，而且作者现在因为工作无暇开发...

**Comment by ApliNi** [comment]
MiraiMC 好像不支持 Fabric. 并且这个插件依赖 Bukkit 和 Spigot, 以及我对模组服了解不多, 可能不会考虑

Edit: 我听说过有可以同时运行插件和模组的服务端, 如果还在的话可以去试一下

**Comment by QianFuv** [comment]
miraimc确实不支持fabric 可以替代的方案是go-cqhttp
至于移植这件事情，我只能说希望可以，因为您现在这个插件功能很完美了qwq
同时运行插件和模组的服务端只有forge+bukkit
而且听说bukkit移植fabric较容易，移植forge较难（
您或许可以尝试一下？

**Comment by ApliNi** [comment]
这可有些麻烦, 连接 go-cqhttp 我都鸽了这么久一笔没动. 这个问题可以开着, 可能以后有时间再来研究吧.   

不过不要指望我能完成它 (

**Comment by QianFuv** [comment]
好啊好啊 我可以等的awa

**Comment by QianFuv** [comment]
目前工作不继续追踪此issue
