### ISSUE TITLE
支持folia

### ISSUE THREAD

**Issue by xiaoluofa** [ApliNi/Chat2QQ#45]

**Comment by ApliNi** [comment]
经过测试, 这个插件能在 Folia 服务器上运行, 但需要修改 MiraiMC 插件的 `paper-plugin.yml` 使其能够被加载
在这里下载: https://modrinth.com/plugin/chat2qq+

**Comment by x1aoren** [comment]
[MiraiMC-Folia.zip](https://github.com/user-attachments/files/16356571/MiraiMC-Folia.zip)

**Comment by x1aoren** [comment]
> [MiraiMC-Folia.zip](https://github.com/user-attachments/files/16356571/MiraiMC-Folia.zip)

@xiaoluofa 
@ApliNi
